### ISSUE TITLE
EventFlow component working prototype delivery

### ISSUE THREAD

**Issue by paulsoh** [linewalks/clinical-charts#13]
**개요 및 요청사항**
EventFlow Component 구현을 위한 작동하는 Prototype을 전달바랍니다.
기대하는 Prototype수준은 [다음](https://gist.github.com/hurcy/ddf0c9f0ac3f6c9f3d4a68f944217673)과 같습니다. 

**결과물**
- Code snippet URL 
- Version이 명시된 의존성 package list (ex: d3@4.13.0, d3-sankey^0.13.0)

**완료 기준**
- [x] @jik0090님의 comment 형태로의 confirm

**Comment by hurcy** [comment]
@jik0090 
결과물이 이 링크에 모두 있습니다. https://codesandbox.io/s/p5lp0y3x6m

**Comment by jik0090** [comment]
https://p5lp0y3x6m.codesandbox.io/
 data-ui/event-flow": "0.0.77"
