### ISSUE TITLE
SankeyChart Story Change

### ISSUE THREAD

**Issue by jik0090** [linewalks/clinical-charts#14]
**개요 및 요청사항**
Storybook에서 Sankey chart의 story들을 구현된 sankeychart에 맞게 재작성 합니다.

**결과물**
- Storybook stories according to [issue](https://github.com/linewalks/catalog/issues/16)

**완료 기준**
- [x] @paulsoh confirmation

**Comment by hurcy** [comment]
@jik0090 이슈 생성할때, 프로젝트랑 마일스톤 꼭 지정해주세요.
