### ISSUE TITLE
EventFlow Component 구현

### ISSUE THREAD

**Issue by jik0090** [linewalks/clinical-charts#20]
**개요 및 요청사항**
Event flow를 React Component로 구현합니다.

**결과물**
- Eventflow를 Storybook에 렌더링 

**완료 기준**
- [x] @paulsoh confirmation

**Comment by jik0090** [comment]
@paulsoh 머지부탁드려요.

**Comment by hurcy** [comment]
수정된 예시 파일입니다.
https://github.com/linewalks/catalog/blob/master/output/eventflow_10_patients.json
https://github.com/linewalks/catalog/blob/master/output/eventflow_100_patients.json
