### ISSUE TITLE
highchart excel export 가능여부

### ISSUE THREAD

**Issue by jik0090** [linewalks/clinical-charts#32]
개요 및 요청사항
highchart excel export 가능여부

결과물
highchart excel export 가능여부 댓글로 확인
export된 예시

완료 기준
* [x] @hurcy  confirmation

**Comment by jik0090** [comment]
https://api.highcharts.com/highcharts/exporting.csv

**Comment by jik0090** [comment]
https://www.highcharts.com/demo/line-basic

차트의 오른쪽위 메뉴를 클릭하면 다운로드 받는 창이 나옵니다.

**Comment by hurcy** [comment]
@jik0090 data sheet + 차트 가 함께 다운로드가 가능한가요?

**Comment by jik0090** [comment]
차트이미지 전체를 jpg,png,pdf,svg형태 다운받을수도 있고, 데이터는 csv,xls로 다운가능합니다.

**Comment by jik0090** [comment]
* exel js api - https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges
* stackoverflow - https://stackoverflow.com/questions/36909463/export-excel-with-header-including-image
