### ISSUE TITLE
HighCharts Component 구현

### ISSUE THREAD

**Issue by jik0090** [linewalks/clinical-charts#33]
개요 및 요청사항
HighChart Component 구현

결과물
HighChart Component - Bar, Line, Pie, Scatter

완료 기준

* [x] bar component @paulsoh confirmation
* [x] line component @paulsoh confirmation
* [x] pie component @paulsoh confirmation
* [x] scatter component @paulsoh confirmation
* [x] @hurcy  confirmation

**Comment by hurcy** [comment]
@jik0090 컴포넌트화 할 차트 종류를 특정해주세요.
기본형 차트 마일스톤에서 구현하실 차트를 모두 포함했으면 좋겠습니다.

@yuna12 차트 종류에 맞춰서 예제 데이터를 준비해주세요.
