### ISSUE TITLE
Table component를 구현합니다

### ISSUE THREAD

**Issue by paulsoh** [linewalks/clinical-charts#43]
**개요 및 요청사항**
다른 Chart component와 같이 사용될 Table component를 조사하고, 구현합니다.
가능하면 기존에 구현되어있는 component를 차용하여 구현합니다

**결과물**
- React Component 
- Storybook stories

**완료 기준**
- [x] Table component의 시안을 @hurcy 님이 confirm합니다
- [x] 구현 결과물은 PR의 형태로 @jik0090 님의 승인을 받습니다.

**Comment by hurcy** [comment]
[테이블 예시](https://docs.google.com/spreadsheets/d/1J1MepkISw-wwIx5G0bG1pEF8kIMInr3J7c_t0YuBTA4/edit?usp=sharing)입니다.

이해를 돕기위해 한글 설명을 추가했습니다. 
시각화는 영어 기준입니다.
