### ISSUE TITLE
Rendering에 필요한 관련 의존성 패키지를 파악합니다

### ISSUE THREAD

**Issue by paulsoh** [linewalks/clinical-charts#6]
의존성 Package를 분석하여 Loader class를 구현합니다.

**Comment by paulsoh** [comment]
@hurcy prototype로 구현하신 Sankey hhart 코드 레벨로 확인 가능한 링크 부탁드립니다.

**Comment by hurcy** [comment]
@paulsoh 

> @hurcy prototype로 구현하신 Sankey hhart 코드 레벨로 확인 가능한 링크 부탁드립니다.

https://gist.github.com/hurcy/ddf0c9f0ac3f6c9f3d4a68f944217673

**Comment by paulsoh** [comment]
의존성 패키지
* d3.v4
  * d3 core library
* d3-sankey-circular
  * d3 + sankey + circular 기능이 구현되어있는 addon 
* d3-scale-chromatic.v1
  * ?
