### ISSUE TITLE
Scatter Chart Test Case 작성

### ISSUE THREAD

**Issue by jik0090** [linewalks/clinical-charts#67]
**개요 및 요청사항**
Scatter Chart에 대한 Unit Test를 작성합니다.

**결과물**
- Scatter Chart Refactoring
- Scatter Chart Test Code

**완료 기준**
- [x] PR Review @paulsoh

**Comment by paulsoh** [comment]
PR text안에 closes #67 이런식으로 작성해놓으면 PR가 닫히고 이슈도 자동으로 닫힙니다~
