### ISSUE TITLE
 Data model을 정의합니다

### ISSUE THREAD

**Issue by paulsoh** [linewalks/clinical-charts#7]

**Comment by hurcy** [comment]
@paulsoh MIMIC-III에서 추출한 Sankey 예시 제공이 가능합니다.
데이터 모델에 협의가 필요하면 말씀해주세요.

- 질병 시퀸스 (CHD -> CHD,MI)
- 투약 시퀸스 (NSAIDs -> Statin)
- 주요 이벤트 시퀸스 (ER Admission->Death)
